# Generated by Django 4.2.6 on 2023-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(blank=True)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('coupon_type', models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default=('percentage', 'percentage'), max_length=50)),
            ],
        ),
    ]
