# Generated by Django 4.2.6 on 2023-11-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
