# Generated by Django 4.2.6 on 2023-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
