# Generated by Django 4.2.6 on 2023-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
