# Generated by Django 4.2.6 on 2023-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
