# Generated by Django 4.2.6 on 2023-11-11 00:58

from django.db import migrations, models
import django.db.models.deletion
import user_side.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0016_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, default=user_side.models.get_default_coupon, on_delete=django.db.models.deletion.CASCADE, to='user_side.coupon'),
        ),
    ]
