# Generated by Django 4.2.6 on 2023-11-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0019_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCoupons',
        ),
    ]
